name: Run JS script

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: Check out code
     uses: actions/checkout@v2

   - name: Setup Node.js environment
     uses: actions/setup-node@v1
     with:
       node-version: '14'

   - name: Run script
     run: |
       cd hbooker
       node getChest.js
